import io
import logging
from typing import Optional, List
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas

from backend.app.schemas.passport import FraudCasePassport

logger = logging.getLogger(__name__)

# Color Palette (SOC / Incident Response Inspired)
COLOR_NAVY_DARK = colors.HexColor("#0f172a")     # Slate 900
COLOR_SLATE_HEADER = colors.HexColor("#1e293b")  # Slate 800
COLOR_SLATE_MUTED = colors.HexColor("#64748b")   # Slate 500
COLOR_SLATE_LIGHT = colors.HexColor("#f1f5f9")   # Slate 100
COLOR_SLATE_BORDER = colors.HexColor("#cbd5e1")  # Slate 300
COLOR_TEXT_MAIN = colors.HexColor("#0f172a")     # Dark Slate
COLOR_CYAN_ACCENT = colors.HexColor("#0284c7")   # Sky 600
COLOR_CRITICAL_RED = colors.HexColor("#b91c1c")  # Red 700
COLOR_HIGH_AMBER = colors.HexColor("#c2410c")    # Amber 700
COLOR_MEDIUM_BLUE = colors.HexColor("#2563eb")   # Blue 600
COLOR_LOW_GREEN = colors.HexColor("#047857")     # Emerald 700

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print 'Page X of Y' 
    and persistent professional headers/footers on each page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_SLATE_MUTED)

        # Header for pages 2+
        if self._pageNumber > 1:
            self.drawString(36, 762, "COUNTERPULSE AI — FRAUD CASE PASSPORT & FORENSIC DOSSIER")
            self.drawRightString(576, 762, "CONFIDENTIAL / LAW ENFORCEMENT & DISPUTE REVIEW")
            self.setStrokeColor(COLOR_SLATE_BORDER)
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)

        # Running Footer on all pages
        self.setStrokeColor(COLOR_SLATE_BORDER)
        self.setLineWidth(0.5)
        self.line(36, 38, 576, 38)

        footer_text = "Generated by CounterPulse AI • AI-generated analysis — human review required"
        self.drawString(36, 26, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 26, page_str)

        self.restoreState()


class PDFReportService:
    """
    Generates high-fidelity, professional incident dossier PDFs from real FraudCasePassport data.
    Ensures safe word-wrapping for long URLs and hash values without overflow.
    """

    def generate_passport_pdf(self, passport: FraudCasePassport) -> bytes:
        """
        Generate a complete, structured PDF dossier from the provided FraudCasePassport.
        Returns raw PDF bytes.
        """
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=46,
            bottomMargin=46,
        )

        # Usable width: 612 - 72 = 540 pt
        usable_width = 540

        styles = getSampleStyleSheet()

        # Custom Typography
        style_title = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            textColor=COLOR_NAVY_DARK,
        )

        style_subtitle = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=COLOR_SLATE_MUTED,
        )

        style_sec_header = ParagraphStyle(
            "SecHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=COLOR_NAVY_DARK,
            spaceAfter=4,
        )

        style_body = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=COLOR_TEXT_MAIN,
        )

        style_body_bold = ParagraphStyle(
            "BodyBold",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=12,
            textColor=COLOR_NAVY_DARK,
        )

        style_table_header = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.white,
        )

        style_table_cell = ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            leading=10,
            textColor=COLOR_TEXT_MAIN,
        )

        style_table_cell_bold = ParagraphStyle(
            "TableCellBold",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            leading=10,
            textColor=COLOR_NAVY_DARK,
        )

        style_table_cell_code = ParagraphStyle(
            "TableCellCode",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=7,
            leading=9,
            textColor=COLOR_TEXT_MAIN,
        )

        style_disclaimer = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=7,
            leading=10,
            textColor=COLOR_SLATE_MUTED,
        )

        story = []

        # -------------------------------------------------------------
        # 1. HEADER BANNER
        # -------------------------------------------------------------
        header_table_data = [
            [
                Paragraph("<b>COUNTERPULSE AI</b>", style_title),
                Paragraph(f"<b>STATUS:</b> {passport.status.upper()}<br/><font color='#64748b'>CASE ID:</font> {passport.case_id}", ParagraphStyle("HRight", parent=style_body, alignment=2)),
            ],
            [
                Paragraph("FRAUD CASE PASSPORT & FORENSIC DOSSIER", ParagraphStyle("SubH", fontName="Helvetica-Bold", fontSize=9, leading=12, textColor=COLOR_CYAN_ACCENT)),
                Paragraph(f"Generated: {passport.updated_at.strftime('%Y-%m-%d %H:%M:%S UTC') if isinstance(passport.updated_at, datetime) else str(passport.updated_at)}", ParagraphStyle("HRightSub", parent=style_subtitle, alignment=2)),
            ]
        ]
        header_table = Table(header_table_data, colWidths=[340, 200])
        header_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
        ]))
        story.append(header_table)
        story.append(Spacer(1, 4))
        story.append(HRFlowable(width="100%", thickness=1.5, color=COLOR_CYAN_ACCENT, spaceAfter=8))

        # -------------------------------------------------------------
        # 2. CASE INFORMATION GRID
        # -------------------------------------------------------------
        severity_color = {
            "critical": COLOR_CRITICAL_RED,
            "high": COLOR_HIGH_AMBER,
            "medium": COLOR_MEDIUM_BLUE,
            "low": COLOR_LOW_GREEN,
        }.get(passport.incident.severity.lower(), COLOR_MEDIUM_BLUE)

        loss_str = "None Reported"
        if passport.financial.loss is not None:
            loss_str = f"{passport.financial.currency} {passport.financial.loss:,.2f}"

        info_data = [
            [
                Paragraph("<b>Incident Title:</b>", style_table_cell_bold),
                Paragraph(passport.title, style_table_cell),
                Paragraph("<b>Scam Typology:</b>", style_table_cell_bold),
                Paragraph(passport.incident.category, style_table_cell),
            ],
            [
                Paragraph("<b>Classification:</b>", style_table_cell_bold),
                Paragraph(passport.incident.incident_type, style_table_cell),
                Paragraph("<b>Severity Rating:</b>", style_table_cell_bold),
                Paragraph(f"<font color='{severity_color.hexval()}'><b>{passport.incident.severity.upper()}</b></font>", style_table_cell),
            ],
            [
                Paragraph("<b>Financial Loss:</b>", style_table_cell_bold),
                Paragraph(f"<b>{loss_str}</b>", style_table_cell),
                Paragraph("<b>Evidence Files:</b>", style_table_cell_bold),
                Paragraph(f"{passport.evidence_count} item(s) processed", style_table_cell),
            ],
        ]
        info_table = Table(info_data, colWidths=[90, 180, 95, 175])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_SLATE_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # 3. INCIDENT SUMMARY & MODUS OPERANDI
        # -------------------------------------------------------------
        story.append(Paragraph("INCIDENT EXECUTIVE SUMMARY", style_sec_header))
        summary_text = passport.incident.summary or "Detailed forensic incident reconstruction is in progress."
        story.append(Paragraph(summary_text, style_body))
        story.append(Spacer(1, 6))

        if passport.incident.modus_operandi:
            story.append(Paragraph("<b>Modus Operandi & Psychological Vectors:</b>", style_body_bold))
            story.append(Paragraph(passport.incident.modus_operandi, style_body))
            story.append(Spacer(1, 8))

        # -------------------------------------------------------------
        # 4. CHRONOLOGICAL TIMELINE
        # -------------------------------------------------------------
        story.append(Spacer(1, 4))
        story.append(Paragraph("CHRONOLOGICAL INCIDENT TIMELINE", style_sec_header))

        if passport.timeline:
            tl_rows = [
                [
                    Paragraph("Timestamp", style_table_header),
                    Paragraph("Event Description", style_table_header),
                    Paragraph("Source Provenance", style_table_header),
                ]
            ]
            for idx, item in enumerate(passport.timeline):
                bg = COLOR_SLATE_LIGHT if idx % 2 == 1 else colors.white
                source_txt = item.source_evidence_id or "Evidence Intake"
                if item.source_reference:
                    source_txt += f"<br/><font color='#64748b'>{item.source_reference}</font>"
                if item.is_inferred:
                    source_txt += "<br/><font color='#c2410c'>[Inferred]</font>"

                tl_rows.append([
                    Paragraph(item.timestamp, style_table_cell_bold),
                    Paragraph(item.event_description, style_table_cell),
                    Paragraph(source_txt, style_table_cell),
                ])

            tl_table = Table(tl_rows, colWidths=[110, 310, 120])
            tl_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), COLOR_SLATE_HEADER),
                ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            for r_idx in range(1, len(tl_rows)):
                if r_idx % 2 == 1:
                    tl_table.setStyle(TableStyle([("BACKGROUND", (0, r_idx), (-1, r_idx), COLOR_SLATE_LIGHT)]))
            story.append(tl_table)
        else:
            story.append(Paragraph("<i>No timeline events recorded.</i>", style_body))

        story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # 5. EXTRACTED FORENSIC INDICATORS (PROVENANCE PRESERVED)
        # -------------------------------------------------------------
        story.append(Paragraph("EXTRACTED FORENSIC INDICATORS", style_sec_header))
        story.append(Paragraph(
            "<font color='#64748b'><i>Note: Indicators represent technical artifacts extracted strictly from uploaded evidence files; they do not establish legal criminality of named account holders.</i></font>",
            style_disclaimer
        ))
        story.append(Spacer(1, 4))

        if passport.indicators:
            ind_rows = [
                [
                    Paragraph("Type", style_table_header),
                    Paragraph("Indicator Value", style_table_header),
                    Paragraph("Confidence", style_table_header),
                    Paragraph("Verification", style_table_header),
                    Paragraph("Evidence Source", style_table_header),
                ]
            ]
            for idx, ind in enumerate(passport.indicators):
                ev_str = ind.source_evidence_id or "—"
                if ind.source_reference:
                    ev_str += f"<br/><font color='#64748b'>{ind.source_reference}</font>"

                # Long values formatting
                val_text = ind.value
                # If very long value without spaces (like long URL or transaction hash), ReportLab Paragraph handles wrapping
                ind_rows.append([
                    Paragraph(ind.indicator_type.replace("_", " ").title(), style_table_cell_bold),
                    Paragraph(val_text, style_table_cell_code),
                    Paragraph(ind.confidence.capitalize(), style_table_cell),
                    Paragraph(ind.verification_status.capitalize(), style_table_cell),
                    Paragraph(ev_str, style_table_cell),
                ])

            ind_table = Table(ind_rows, colWidths=[80, 180, 65, 75, 140])
            ind_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), COLOR_SLATE_HEADER),
                ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            for r_idx in range(1, len(ind_rows)):
                if r_idx % 2 == 1:
                    ind_table.setStyle(TableStyle([("BACKGROUND", (0, r_idx), (-1, r_idx), COLOR_SLATE_LIGHT)]))
            story.append(ind_table)
        else:
            story.append(Paragraph("<i>No forensic indicators extracted.</i>", style_body))

        story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # 6. COMPROMISE ASSESSMENT (4-TIER MODEL)
        # -------------------------------------------------------------
        story.append(Paragraph("SYSTEMIC COMPROMISE ASSESSMENT", style_sec_header))

        if passport.compromise:
            comp_rows = [
                [
                    Paragraph("Category", style_table_header),
                    Paragraph("Risk Status", style_table_header),
                    Paragraph("Forensic Findings", style_table_header),
                    Paragraph("Recommended Containment", style_table_header),
                    Paragraph("Evidence", style_table_header),
                ]
            ]
            for idx, comp in enumerate(passport.compromise):
                status_color = "#b91c1c" if comp.risk_level.upper() in ("CONFIRMED", "INSTALLED") else ("#c2410c" if comp.risk_level.upper() == "DISCLOSED" else "#2563eb")
                ev_str = comp.source_evidence_id or "—"
                if comp.source_reference:
                    ev_str += f"<br/><font color='#64748b'>{comp.source_reference}</font>"

                comp_rows.append([
                    Paragraph(comp.category.replace("_", " ").upper(), style_table_cell_bold),
                    Paragraph(f"<font color='{status_color}'><b>{comp.risk_level.upper()}</b></font>", style_table_cell),
                    Paragraph(comp.details, style_table_cell),
                    Paragraph(comp.recommended_action, style_table_cell),
                    Paragraph(ev_str, style_table_cell),
                ])

            comp_table = Table(comp_rows, colWidths=[85, 75, 160, 140, 80])
            comp_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), COLOR_SLATE_HEADER),
                ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            for r_idx in range(1, len(comp_rows)):
                if r_idx % 2 == 1:
                    comp_table.setStyle(TableStyle([("BACKGROUND", (0, r_idx), (-1, r_idx), COLOR_SLATE_LIGHT)]))
            story.append(comp_table)
        else:
            story.append(Paragraph("<i>No compromise vectors flagged.</i>", style_body))

        story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # 7. IMMEDIATE ACTIONS & CONTAINMENT
        # -------------------------------------------------------------
        if passport.immediate_actions:
            act_flowables = [
                Paragraph("PRIORITIZED IMMEDIATE ACTIONS & CONTAINMENT", style_sec_header)
            ]
            for idx, act in enumerate(passport.immediate_actions, 1):
                act_flowables.append(
                    Paragraph(f"<b>{idx}.</b> {act}", style_body)
                )
                act_flowables.append(Spacer(1, 2))
            story.append(KeepTogether(act_flowables))
            story.append(Spacer(1, 8))

        # -------------------------------------------------------------
        # 8. EVIDENCE AUDIT & PROVENANCE MAP
        # -------------------------------------------------------------
        if passport.evidence_items:
            ev_flowables = [
                Paragraph("INGESTED EVIDENCE & PROVENANCE AUDIT", style_sec_header)
            ]
            ev_table_rows = [
                [
                    Paragraph("Evidence ID", style_table_header),
                    Paragraph("Type", style_table_header),
                    Paragraph("Original Filename", style_table_header),
                    Paragraph("Status", style_table_header),
                    Paragraph("Extracted Facts", style_table_header),
                ]
            ]
            for ev in passport.evidence_items:
                ev_table_rows.append([
                    Paragraph(ev.evidence_id, style_table_cell_code),
                    Paragraph(ev.evidence_type.upper(), style_table_cell),
                    Paragraph(ev.filename, style_table_cell),
                    Paragraph(ev.processing_status.upper(), style_table_cell),
                    Paragraph(f"{ev.facts_count} item(s) cited", style_table_cell_bold),
                ])

            ev_audit_table = Table(ev_table_rows, colWidths=[90, 60, 200, 80, 110])
            ev_audit_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), COLOR_SLATE_HEADER),
                ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            ev_flowables.append(ev_audit_table)
            story.append(KeepTogether(ev_flowables))
            story.append(Spacer(1, 10))

        # -------------------------------------------------------------
        # 9. STATUTORY DISCLAIMER
        # -------------------------------------------------------------
        disclaimer_box = [
            Paragraph("<b>IMPORTANT NOTICE & LEGAL DISCLAIMER:</b>", ParagraphStyle("DiscHead", parent=style_disclaimer, fontName="Helvetica-Bold", textColor=COLOR_NAVY_DARK)),
            Spacer(1, 2),
            Paragraph(passport.disclaimer, style_disclaimer),
            Spacer(1, 2),
            Paragraph(
                "This document has been synthesized autonomously by CounterPulse AI based strictly on the uploaded evidence artifacts. "
                "It serves as a structured reference dossier for the victim, their banking ombudsman, and law enforcement authorities (1930 / NCRP). "
                "Any formal complaints or legal disputes must be reviewed and approved by the victim or authorized legal counsel.",
                style_disclaimer
            ),
        ]
        disc_table = Table([[disclaimer_box]], colWidths=[usable_width])
        disc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_SLATE_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_SLATE_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(disc_table)

        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        return buf.getvalue()

pdf_report_service = PDFReportService()
