from typing import List, Optional, Dict, Any, Literal
from datetime import datetime, timezone
from pydantic import BaseModel, Field

class IncidentPassportInfo(BaseModel):
    incident_type: str = Field("Financial Fraud", description="High-level incident classification (e.g. Financial Fraud, Identity Extortion)")
    category: str = Field(..., description="Specific scam typology (e.g. Digital Arrest, Part-Time Job Scam, UPI Phishing)")
    severity: str = Field("medium", description="Severity rating: critical, high, medium, low")
    summary: str = Field(..., description="Comprehensive executive summary of the incident")
    modus_operandi: Optional[str] = Field(None, description="Step-by-step psychological tactics and attack vectors")

class FinancialPassportInfo(BaseModel):
    loss: Optional[float] = Field(None, description="Confirmed or claimed monetary loss amount")
    currency: str = Field("INR", description="Currency identifier (default: INR)")
    transactions: List[Dict[str, Any]] = Field(default_factory=list, description="Extracted transaction items with amounts and provenance")

class TimelinePassportItem(BaseModel):
    timestamp: str = Field(..., description="Timestamp or milestone indicator")
    event_description: str = Field(..., description="Chronological incident event description")
    source_evidence_id: Optional[str] = Field(None, description="Evidence ID from which this milestone is derived")
    source_reference: Optional[str] = Field(None, description="Specific quotation or reference excerpt")
    is_inferred: bool = Field(False, description="True if inferred by reasoning agent; False if directly recorded")
    confidence: str = Field("high", description="Milestone extraction confidence")

class IndicatorPassportItem(BaseModel):
    indicator_type: str = Field(..., description="Forensic indicator type: phone_number, upi_id, url, email, suspect_name, organization, account_number, transaction_id")
    value: str = Field(..., description="Exact indicator value")
    confidence: str = Field("medium", description="Extraction confidence: high, medium, low")
    verification_status: str = Field("unverified", description="Provenance status: supported, possible, unverified, not_found")
    source_evidence_id: Optional[str] = Field(None, description="Originating evidence ID (e.g. EV-XXXXXXXX)")
    source_reference: Optional[str] = Field(None, description="Specific citation or excerpt from evidence")

class CompromisePassportItem(BaseModel):
    category: str = Field(..., description="Compromise vector: banking, credentials, remote_access, pii, identity_information, otp_authentication, device")
    risk_level: str = Field(..., description="Assessed status: CONFIRMED, INSTALLED, DISCLOSED, REQUESTED, POSSIBLE, NOT_FOUND")
    details: str = Field(..., description="Forensic reasoning strictly grounded in uploaded evidence")
    recommended_action: str = Field(..., description="Actionable victim containment instruction")
    source_evidence_id: Optional[str] = Field(None, description="Supporting evidence ID")
    source_reference: Optional[str] = Field(None, description="Specific evidence quotation or excerpt")

class EvidenceProvenanceItem(BaseModel):
    evidence_id: str
    evidence_type: str
    filename: str
    processing_status: str
    created_at: datetime
    facts_count: int = 0

class FraudCasePassport(BaseModel):
    case_id: str = Field(..., description="Unique case identifier")
    title: str = Field("Untitled Incident", description="Case title")
    description: Optional[str] = Field(None, description="Case intake description")
    status: str = Field("passport_ready", description="Current investigation status")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    incident: IncidentPassportInfo
    financial: FinancialPassportInfo
    timeline: List[TimelinePassportItem] = Field(default_factory=list)
    indicators: List[IndicatorPassportItem] = Field(default_factory=list)
    compromise: List[CompromisePassportItem] = Field(default_factory=list)
    immediate_actions: List[str] = Field(default_factory=list)
    evidence_items: List[EvidenceProvenanceItem] = Field(default_factory=list)
    evidence_count: int = 0
    disclaimer: str = Field(
        "Extracted indicators represent investigative artifacts; they do not establish criminality of named individuals. "
        "Generated by CounterPulse AI — human review required.",
        description="Statutory legal and investigative disclaimer"
    )

    class Config:
        from_attributes = True
